### ISSUE TITLE
Phrase source is incorrect

### ISSUE THREAD

**Issue by Raphi44** [zuhito/node-red-contrib-google-translate#2]
Hi,

The phrase to translate is not taken from the correct place according to your readme, readme says 'msg.payload.phrase' and according to code its 'msg.payload.input', please view the following:
readme:
<img width="471" alt="image" src="https://user-images.githubusercontent.com/80213993/199956182-cb9cfa1c-096a-496e-9ba1-d5561d05bd7c.png">

code: 
<img width="515" alt="image" src="https://user-images.githubusercontent.com/80213993/199956303-7c27a479-129d-4228-8e28-3c9e339f6d1d.png">

Thanks.

**Comment by kazuhitoyokoi** [comment]
You're using other forked nodes. Could you post your issue on the following repository?
https://github.com/6ebeng/translate-red-node
https://github.com/idocme/translate-red-node
